title: "functional fascinations"
author: "Chris Rybicki"

theme: minima

repository: Chriscbr/blog

twitter_username: rybickic
github_username:  Chriscbr
linkedin_username: christopher-rybicki
rss: rss

google_analytics: G-P0N4J11SYF

baseurl: /blog
